name: CI

on:
  push:
    branches:
    - master
    - docs/add-repository-guidelines
  pull_request:

jobs:
  contract-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.16.0

    - name: Install dependencies
      run: npm ci

    - name: Contract tests
      run: npm run test:contract

    - name: Lint
      run: npx eslint src cloudflare/test build

    - name: Build self-hosted Web client
      run: npm run build:selfhosted

    - name: Build self-hosted extensions
      run: npm run build:extension:selfhosted
